### ISSUE TITLE
[1.12.2] Issue with the witch loot table

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/ERZ#20]
There's an error log but I'm pretty sure this is the only relevant part of the log.
>Couldn't load loot table emberroot:entity/witch from jar:file ...
>com.google.gson.JsonParseException: Loot Table "emberroot:entity/witch" Missing `name` entry for pool #0

**Comment by Lothrazar** [comment]
Yep when a witch dies it logs this 

`    [00:00:06] [Server thread/ERROR]: Couldn't load loot table emberroot:entity/witch from file:/Q:/CODE/minecraft/eclipseWorkspace/roots/bin/assets/emberroot/loot_tables/entity/witch.json
com.google.gson.JsonParseException: Loot Table "emberroot:entity/witch" Missing `name` entry for pool #0
	at net.minecraftforge.common.ForgeHooks.readPoolName(ForgeHooks.java:1200) ~[ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:152) ~[LootPool$Serializer.class:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:147) ~[LootPool$Serializer.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(JsonUtils.java:359) ~[JsonUtils.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(JsonUtils.java:381) ~[JsonUtils.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:210) ~[LootTable$Serializer.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:205) ~[LootTable$Serializer.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[Gson.class:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1124) ~[ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.loadBuiltinLootTable(LootTableManager.java:156) [LootTableManager$Loader.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:72) [LootTableManager$Loader.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:53) [LootTableManager$Loader.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [guava-21.0.jar:?]
	at net.minecraft.world.storage.loot.LootTableManager.getLootTableFromLocation(LootTableManager.java:40) [LootTableManager.class:?]
	at net.minecraft.entity.EntityLiving.dropLoot(EntityLiving.java:595) [EntityLiving.class:?]
	at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1311) [EntityLivingBase.class:?]
	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1127) [EntityLivingBase.class:?]
	at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:80) [EntityMob.class:?]
	at net.minecraft.entity.projectile.EntityArrow.onHit(EntityArrow.java:391) [EntityArrow.class:?]
	at net.minecraft.entity.projectile.EntityArrow.onUpdate(EntityArrow.java:286) [EntityArrow.class:?]
	at net.minecraft.entity.projectile.EntityTippedArrow.onUpdate(EntityTippedArrow.java:110) [EntityTippedArrow.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2141) [World.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:872) [WorldServer.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2101) [World.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1912) [World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:644) [WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:836) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:740) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:589) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]        `

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/emberroot-zoo/files/2543368
